site_name: FM Receiver
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - Scanner: scanner.md
  - About: about.md  
  # - Installation: installation.md
  # - Getting Started: getting-started.md
  # - Functions:
  #     - Overview: functions/index.md
  # - Troubleshooting: troubleshooting.md
  # - FAQ: faq.md
theme: readthedocs