[project]
name = "fm-application"
version = "0.1.0"
description = "GNU Radio FM receiver application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.5.0",
]

[project.scripts]
setup-gnuradio = "scripts.setup_gnuradio:main"
