[project]
name = "fm-application"
version = "0.1.0"
description = "GNU Radio FM receiver application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.5.0",
    "numpy>=1.21.0",
    "pyqt5>=5.15.0",
    "qtpy>=2.3.0",
]
